version: '2.1'

services:

  security:
    build: ./sample-service
    ports:
     - "8123:8123"
#    depends_on:
#     db:
#       condition: service_healthy
    environment:
     - DATABASE_HOST=db
     - DATABASE_USER=users_service
     - DATABASE_PASSWORD=123
     - DATABASE_NAME=CHIRINOS
     - DATABASE_PORT=3306
     - DATABASE_QUERY=SELECT @@version;
    volumes:
     - ./sample-service/api:/app/api

#  db:
#    build: ./database-service
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--protocol", "TCP", "-P", "3306", "-p123"]
#      interval: 2s
#      timeout: 1s
#      retries: 20
